### ISSUE TITLE
关于lvis最终复现效果咨询

### ISSUE THREAD

**Issue by rookietyper** [DongSky/P_ASL_LVIS_reproduce#1]

**Comment by rookietyper** [comment]
您好，请问您最终得到论文中得到的lvis效果了吗，具体是怎么操作的呢

**Comment by DongSky** [comment]
作者在官方的repository里提供了一个对应的data loader，训练后基本就接近论文中的性能了。

**Comment by rookietyper** [comment]
十分感谢大佬了，请问您把这部分加到自己的代码中了吗，我可以直接跑您的模型吗，如果没有能麻烦问下这块具体在原repository的哪部分吗？

**Comment by rookietyper** [comment]
我看他在您21年12月5号问之后，只加了一些计算AP的脚本，请问您所说的对应的data loader具体是指什么呢

**Comment by DongSky** [comment]
sorry，我的口误，原文是“partial-mAP metric to the code (in helper_functions.py)”，我应该是根据他的意见做了下修改。你也可以看一下他的repository，毕竟他的是官方的，我的这个修正后还没有提交到自己的repo上。

**Comment by rookietyper** [comment]
我看他的回复是第一次训练换成了negative，然后换一种评测方式（也就是partial-mAP），然后除此之外没有变化了。我在跑您的代码的时候，也是换成了第一次用negative，第二次用selective，在用您原有的评测方式的情况下评测（没用partial-mAP），然后参数都是用您调的，最多我看在验证集上就是64.多，请问这样是没问题的是吧，说明主要问题就是在评测方式上是吧？
（抱歉问的有些多，真的希望您能继续回复，谢谢您了！！！）
